#!/bin/bash

#Extract the number of instructions, number of data accesses, number of cache misses from the data files generated by cachegrind

BENCHMARK_DIR=$"/home/Bruna/valgrind_tum/new_results/results_pca/"
#benchmark_name=$2

SIZES=(1024 2048 4096 8192 16384 32768 65536 131072 262144 524288 1048576 2097152 4194304 8388608)
WAYS=(1 2 4 8 16 32)
#POLICIES=('lru' 'lip' 'random' 'fifo' 'bip0.015625' 'bip0.03125' 'bip0.0625')
#BENCHMARKS=("kmeans-large" "kmeans-medium" "kmeans-small" "disparity-cif" "disparity-fullhd" "disparity-qcif" "disparity-vga" "lda-large" "lda-medium" "lda-small" "liblinear-tlarge" "liblinear-tmedium" "liblinear-tsmall" "me-large" "me-medium" "me-small" "mser-cif" "mser-fullhd" "mser-qcif" "multi_ncut-cif" "multi_ncut-fullhd" "multi_ncut-qcif" "pca-large" "pca-medium" "pca-small" "rbm-large" "rbm-medium" "rbm-small" "sift-cif" "sift-fullhd" "sift-qcif" "sift-vga" "spc-large" "spc-medium" "spc-small" "sphinx-large" "sphinx-medium" "sphinx-small" "stitch-cif" "stitch-fullhd" "stitch-vga" "svd3-large" "texture_synthesis-cif" "texture_synthesis-fullhd" "tracking-cif" "tracking-fullhd" "tracking-vga")
BENCHMARKS=("pca-small")
#missing: "svd3-medium" "svd3-small" "srr-large" "srr-medium" "srr-small"

cd $BENCHMARK_DIR

for benchmark_name in ${BENCHMARKS[@]}
do
    for w in ${WAYS[@]}
    do
        output_file=$benchmark_name\_$w\ways"_filtered.csv"
        echo "Generating the results for the $benchmark_name with $w ways"
        #echo "SIZE LRU-I LRU-D LRU-M LIP-I LIP-D LIP-M RANDOM-I RANDOM-D RANDOM-M FIFO-I FIFO-D FIFO-M" > $output_file
        #printf "%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s\n" "SIZE" "LRU-I" "LRU-D" "LRU-M" "LIP-I" "LIP-D" "LIP-M" "RANDOM-I" "RANDOM-D" "RANDOM-M" "FIFO-I" "FIFO-D" "FIFO-M" "BIP0.015625-I" "BIP0.015625-D" "BIP0.015625-M" "BIP0.03125-I" "BIP0.03125-D" "BIP0.03125-M" "BIP0.0625-I" "BIP0.0625-D" "BIP0.0625-M"> $output_file
        printf "%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s\n" "SIZE" "LRU-I" "LRU-D" "LRU-M" "BIP0.015625-I" "BIP0.015625-D" "BIP0.015625-M" "BIP0.03125-I" "BIP0.03125-D" "BIP0.03125-M" "BIP0.0625-I" "BIP0.0625-D" "BIP0.0625-M" "DIP0.015625-I" "DIP0.015625-D" "DIP0.015625-M" "DIP0.03125-I" "DIP0.03125-D" "DIP0.03125-M" "DIP0.0625-I" "DIP0.0625-D" "DIP0.0625-M"> $output_file

        for s in ${SIZES[@]}
        do
            filename_lru=$(echo results_$benchmark_name\_$s\_$w\ways\_lru.log)
            #filename_lip=$(echo results_$benchmark_name\_$s\_$w\ways\_lip.log)
            #filename_random=$(echo results_$benchmark_name\_$s\_$w\ways\_random.log)
            #filename_fifo=$(echo results_$benchmark_name\_$s\_$w\ways\_fifo.log)
            filename_bip0015625=$(echo results_$benchmark_name\_$s\_$w\ways\_bip0.015625.log)
            filename_bip003125=$(echo results_$benchmark_name\_$s\_$w\ways\_bip0.03125.log)
            filename_bip00625=$(echo results_$benchmark_name\_$s\_$w\ways\_bip0.0625.log)
            filename_dip0015625=$(echo results_$benchmark_name\_$s\_$w\ways\_dip0.015625.log)
            filename_dip003125=$(echo results_$benchmark_name\_$s\_$w\ways\_dip0.03125.log)
            filename_dip00625=$(echo results_$benchmark_name\_$s\_$w\ways\_dip0.0625.log)

            irefs_lru=$(cat $filename_lru | grep "I   refs:" | awk '{print $4}' |  sed s/,//g)
            drefs_lru=$(cat $filename_lru | grep "D   refs:" | awk '{print $4}' |  sed s/,//g)
            dmiss_lru=$(cat $filename_lru | grep "D1  misses" | awk '{print $4}' |  sed s/,//g)

            #echo "LRU: Number of instructions: $irefs_lru, Data accesses: $drefs_lru, Number of misses: $dmiss_lru"

            #irefs_lip=$(cat $filename_lip | grep "I   refs:" | awk '{print $4}' |  sed s/,//g)
            #drefs_lip=$(cat $filename_lip | grep "D   refs:" | awk '{print $4}' |  sed s/,//g)
            #dmiss_lip=$(cat $filename_lip | grep "D1  misses" | awk '{print $4}' |  sed s/,//g)

            #echo "LIP: Number of instructions: $irefs_lip, Data accesses: $drefs_lip, Number of misses: $dmiss_lip"

            #irefs_rand=$(cat $filename_random | grep "I   refs:" | awk '{print $4}' |  sed s/,//g)
            #drefs_rand=$(cat $filename_random | grep "D   refs:" | awk '{print $4}' |  sed s/,//g)
            #dmiss_rand=$(cat $filename_random | grep "D1  misses" | awk '{print $4}' |  sed s/,//g)

            #echo "RANDOM: Number of instructions: $irefs_rand, Data accesses: $drefs_rand, Number of misses: $dmiss_rand"

            #irefs_fifo=$(cat $filename_fifo | grep "I   refs:" | awk '{print $4}' |  sed s/,//g)
            #drefs_fifo=$(cat $filename_fifo | grep "D   refs:" | awk '{print $4}' |  sed s/,//g)
            #dmiss_fifo=$(cat $filename_fifo | grep "D1  misses" | awk '{print $4}' |  sed s/,//g)

            #echo "FIFO: Number of instructions: $irefs_fifo, Data accesses: $drefs_fifo, Number of misses: $dmiss_fifo"

            irefs_bip0015625=$(cat $filename_bip0015625 | grep "I   refs:" | awk '{print $4}' |  sed s/,//g)
            drefs_bip0015625=$(cat $filename_bip0015625 | grep "D   refs:" | awk '{print $4}' |  sed s/,//g)
            dmiss_bip0015625=$(cat $filename_bip0015625 | grep "D1  misses" | awk '{print $4}' |  sed s/,//g)

            #echo "BIP0015625: Number of instructions: $irefs_bip0015625, Data accesses: $drefs_bip0015625, Number of misses: $dmiss_bip0015625"

            irefs_bip003125=$(cat $filename_bip003125 | grep "I   refs:" | awk '{print $4}' |  sed s/,//g)
            drefs_bip003125=$(cat $filename_bip003125 | grep "D   refs:" | awk '{print $4}' |  sed s/,//g)
            dmiss_bip003125=$(cat $filename_bip003125 | grep "D1  misses" | awk '{print $4}' |  sed s/,//g)

            #echo "BIP003125: Number of instructions: $irefs_bip003125, Data accesses: $drefs_bip003125, Number of misses: $dmiss_bip003125"

            irefs_bip00625=$(cat $filename_bip00625 | grep "I   refs:" | awk '{print $4}' |  sed s/,//g)
            drefs_bip00625=$(cat $filename_bip00625 | grep "D   refs:" | awk '{print $4}' |  sed s/,//g)
            dmiss_bip00625=$(cat $filename_bip00625 | grep "D1  misses" | awk '{print $4}' |  sed s/,//g)

            #echo "BIP00625: Number of instructions: $irefs_bip00625, Data accesses: $drefs_bip00625, Number of misses: $dmiss_bip00625"

            irefs_dip0015625=$(cat $filename_dip0015625 | grep "I   refs:" | awk '{print $4}' |  sed s/,//g)
            drefs_dip0015625=$(cat $filename_dip0015625 | grep "D   refs:" | awk '{print $4}' |  sed s/,//g)
            dmiss_dip0015625=$(cat $filename_dip0015625 | grep "D1  misses" | awk '{print $4}' |  sed s/,//g)

            #echo "BIP0015625: Number of instructions: $irefs_bip0015625, Data accesses: $drefs_bip0015625, Number of misses: $dmiss_bip0015625"

            irefs_dip003125=$(cat $filename_dip003125 | grep "I   refs:" | awk '{print $4}' |  sed s/,//g)
            drefs_dip003125=$(cat $filename_dip003125 | grep "D   refs:" | awk '{print $4}' |  sed s/,//g)
            dmiss_dip003125=$(cat $filename_dip003125 | grep "D1  misses" | awk '{print $4}' |  sed s/,//g)

            #echo "BIP003125: Number of instructions: $irefs_bip003125, Data accesses: $drefs_bip003125, Number of misses: $dmiss_bip003125"

            irefs_dip00625=$(cat $filename_dip00625 | grep "I   refs:" | awk '{print $4}' |  sed s/,//g)
            drefs_dip00625=$(cat $filename_dip00625 | grep "D   refs:" | awk '{print $4}' |  sed s/,//g)
            dmiss_dip00625=$(cat $filename_dip00625 | grep "D1  misses" | awk '{print $4}' |  sed s/,//g)

            #echo "BIP00625: Number of instructions: $irefs_bip00625, Data accesses: $drefs_bip00625, Number of misses: $dmiss_bip00625"

            #printf "%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d\n" $s $irefs_lru $drefs_lru $dmiss_lru $irefs_lip $drefs_lip $dmiss_lip $irefs_rand $drefs_rand $dmiss_rand $irefs_fifo $drefs_fifo $dmiss_fifo $irefs_bip0015625 $drefs_bip0015625 $dmiss_bip0015625 $irefs_bip003125 $drefs_bip003125 $dmiss_bip003125 $irefs_bip00625 $drefs_bip00625 $dmiss_bip00625 >> $output_file
            printf "%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d\n" $s $irefs_lru $drefs_lru $dmiss_lru $irefs_bip0015625 $drefs_bip0015625 $dmiss_bip0015625 $irefs_bip003125 $drefs_bip003125 $dmiss_bip003125 $irefs_bip00625 $drefs_bip00625 $dmiss_bip00625 $irefs_dip0015625 $drefs_dip0015625 $dmiss_dip0015625 $irefs_dip003125 $drefs_dip003125 $dmiss_dip003125 $irefs_dip00625 $drefs_dip00625 $dmiss_dip00625 >> $output_file
        done
    done
done
cd - &> /dev/null
